checkpoint:
  async_saving: false
  broadcast_via_filesystem: true
  dcp_async_mode_enabled: false
  jit:
    device: cuda
    dtype: bfloat16
    enabled: false
    input_shape: null
    strict: true
  keys_not_to_resume: []
  load_ema_to_reg: false
  load_path: /workspace/checkpoints/Cosmos-Predict1-7B-Text2World/model.pt
  load_training_state: false
  only_load_scheduler_state: false
  save_iter: 1000
  strict_resume: false
  type:
    _target_: <class 'cosmos_predict1.checkpointer.peft_checkpointer.Checkpointer'>
  verbose: true
dataloader_train:
  _target_: <class 'torch.utils.data.dataloader.DataLoader'>
  batch_sampler: null
  batch_size: '1'
  collate_fn: null
  dataset:
    _target_: <class 'cosmos_predict1.diffusion.training.datasets.dataset_video.Dataset'>
    dataset_dir: /workspace/datasets/posttrain_panda70m/vehicle
    num_frames: '121'
    sequence_interval: '1'
    start_frame_interval: '1'
    video_size:
    - '384'
    - '384'
  drop_last: 'True'
  generator: null
  multiprocessing_context: null
  num_workers: '8'
  persistent_workers: 'False'
  pin_memory: 'True'
  pin_memory_device: ''
  prefetch_factor: null
  sampler:
    _target_: <function get_sampler at 0x7f7b9afee3b0>
    dataset:
      _target_: <class 'cosmos_predict1.diffusion.training.datasets.dataset_video.Dataset'>
      dataset_dir: /workspace/datasets/posttrain_panda70m/vehicle
      num_frames: '121'
      sequence_interval: '1'
      start_frame_interval: '1'
      video_size:
      - '384'
      - '384'
  shuffle: null
  timeout: '0'
  worker_init_fn: null
dataloader_val:
  _target_: <class 'torch.utils.data.dataloader.DataLoader'>
  batch_sampler: null
  batch_size: '1'
  collate_fn: null
  dataset:
    _target_: <class 'cosmos_predict1.diffusion.training.datasets.dataset_video.Dataset'>
    dataset_dir: /workspace/datasets/posttrain_panda70m/vehicle
    num_frames: '121'
    sequence_interval: '1'
    start_frame_interval: '1'
    video_size:
    - '384'
    - '384'
  drop_last: 'True'
  generator: null
  multiprocessing_context: null
  num_workers: '8'
  persistent_workers: 'False'
  pin_memory: 'True'
  pin_memory_device: ''
  prefetch_factor: null
  sampler:
    _target_: <function get_sampler at 0x7f7b9afee3b0>
    dataset:
      _target_: <class 'cosmos_predict1.diffusion.training.datasets.dataset_video.Dataset'>
      dataset_dir: /workspace/datasets/posttrain_panda70m/vehicle
      num_frames: '121'
      sequence_interval: '1'
      start_frame_interval: '1'
      video_size:
      - '384'
      - '384'
  shuffle: null
  timeout: '0'
  worker_init_fn: null
defaults:
- _self_
- data_train: null
- data_val: null
- optimizer: fusedadamw
- scheduler: lambdalinear
- callbacks: null
- net: null
- conditioner: add_fps_image_size_padding_mask
- fsdp: null
- ema: power
- vae: vae1
- checkpoint: pbss
- ckpt_klass: fsdp
- experiment: null
job:
  group: diffusion_text2world
  name: text2world_7b_lora_panda70m_vehicle_test
  project: posttraining
model:
  adjust_video_noise: 'False'
  aesthetic_finetuning:
    enabled: 'False'
  camera_sample_weight:
    enabled: 'False'
    weight: '5.0'
  conditioner:
    _target_: <class 'cosmos_predict1.diffusion.training.conditioner.VideoConditioner'>
    fps:
      dropout_rate: 0.0
      input_key: fps
      obj:
        _target_: <class 'cosmos_predict1.diffusion.config.base.conditioner.ReMapkey'>
        dtype: null
        output_key: fps
    image_size:
      dropout_rate: 0.0
      input_key: image_size
      obj:
        _target_: <class 'cosmos_predict1.diffusion.config.base.conditioner.ReMapkey'>
        dtype: null
        output_key: image_size
    num_frames:
      dropout_rate: 0.0
      input_key: num_frames
      obj:
        _target_: <class 'cosmos_predict1.diffusion.config.base.conditioner.ReMapkey'>
        dtype: null
        output_key: num_frames
    padding_mask:
      dropout_rate: 0.0
      input_key: padding_mask
      obj:
        _target_: <class 'cosmos_predict1.diffusion.config.base.conditioner.ReMapkey'>
        dtype: null
        output_key: padding_mask
    text:
      dropout_rate: 0.2
      input_keys:
      - t5_text_embeddings
      - t5_text_mask
      obj:
        _target_: <class 'cosmos_predict1.diffusion.conditioner.TextAttr'>
  ema:
    _target_: <bound method PowerEMATracker.initialize_multi_rank_ema of <class 'cosmos_predict1.utils.ema.PowerEMATracker'>>
    enabled: 'False'
    model: null
    num: '3'
    rate: '0.1'
  fsdp:
    checkpoint: 'False'
    min_num_params: '1024'
    policy: block
    sharding_group_size: '8'
    sharding_strategy: full
  fsdp_enabled: 'False'
  input_data_key: video
  input_image_key: images_1024
  latent_shape:
  - '16'
  - '16'
  - '48'
  - '48'
  loss_add_logvar: 'True'
  loss_mask_enabled: 'False'
  loss_masking: null
  loss_reduce: mean
  loss_scale: '1.0'
  net:
    _target_: <class 'cosmos_predict1.diffusion.training.networks.general_dit.GeneralDIT'>
    adaln_lora_dim: '256'
    additional_timestamp_channels: null
    affline_emb_norm: 'True'
    block_config: FA-CA-MLP
    block_x_format: THWBD
    concat_padding_mask: 'True'
    crossattn_emb_channels: '1024'
    extra_h_extrapolation_ratio: '1.0'
    extra_per_block_abs_pos_emb: 'True'
    extra_per_block_abs_pos_emb_type: learnable
    extra_t_extrapolation_ratio: '1.0'
    extra_w_extrapolation_ratio: '1.0'
    in_channels: '16'
    layer_mask: null
    legacy_patch_emb: 'False'
    max_fps: '30'
    max_frames: '128'
    max_img_h: '240'
    max_img_w: '240'
    min_fps: '1'
    mlp_ratio: '4.0'
    model_channels: '4096'
    num_blocks: '28'
    num_heads: '32'
    out_channels: '16'
    patch_spatial: '2'
    patch_temporal: '1'
    pos_emb_cls: rope3d
    pos_emb_interpolation: crop
    pos_emb_learnable: 'False'
    rope_h_extrapolation_ratio: '1'
    rope_t_extrapolation_ratio: '2'
    rope_w_extrapolation_ratio: '1'
    spatial_attn_win_size: '1'
    temporal_attn_win_size: '1'
    use_adaln_lora: 'True'
    use_checkpoint: 'False'
    use_cross_attn_mask: 'False'
    use_memory_save: 'False'
    window_block_indexes: []
    window_sizes: []
  num_latents_to_drop: '0'
  peft_control:
    customization_type: LoRA
    edits:
    - block_edit:
      - FA[to_q, to_v]
      - CA[to_q, to_v]
      blocks: \b(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27)\b
      customization_type: LoRA
      rank: '8'
      scale: '1'
    enabled: 'True'
    rank: '8'
    scale: '1'
  precision: bfloat16
  sde:
    _target_: <class 'cosmos_predict1.diffusion.training.modules.edm_sde.EDMSDE'>
    p_mean: '0.0'
    p_std: '1.0'
    sigma_max: '80'
    sigma_min: '0.0002'
  sigma_data: '0.5'
  use_dummy_temporal_dim: 'False'
  use_torch_compile: 'False'
  vae:
    _target_: <class 'cosmos_predict1.diffusion.training.module.pretrained_vae.VideoJITTokenizer'>
    dec_fp: /workspace/checkpoints/Cosmos-Tokenize1-CV8x8x8-720p/decoder.jit
    enc_fp: /workspace/checkpoints/Cosmos-Tokenize1-CV8x8x8-720p/encoder.jit
    is_bf16: 'True'
    latent_ch: '16'
    max_dec_batch_size: '4'
    max_enc_batch_size: '8'
    mean_std_fp: /workspace/checkpoints/Cosmos-Tokenize1-CV8x8x8-720p/mean_std.pt
    name: cosmos_diffusion_tokenizer_comp8x8x8
    pixel_chunk_duration: '121'
    spatial_compression_factor: '8'
    spatial_resolution: '720'
    temporal_compression_factor: '8'
model_obj:
  _target_: <class 'cosmos_predict1.diffusion.training.models.model_peft.video_peft_decorator.<locals>.PEFTVideoDiffusionModel'>
  config: null
  fsdp_checkpointer: null
model_parallel:
  _cpu_offloading_context: null
  async_tensor_model_parallel_allreduce: false
  autocast_dtype: torch.float32
  barrier_with_L1_time: true
  batch_p2p_comm: true
  batch_p2p_sync: true
  bf16: false
  context_parallel_size: 1
  cpu_offloading: false
  cpu_offloading_activations: true
  cpu_offloading_num_layers: 0
  cpu_offloading_weights: true
  cross_entropy_loss_fusion: false
  deallocate_pipeline_outputs: false
  defer_embedding_wgrad_compute: false
  deterministic_mode: false
  enable_autocast: false
  expert_model_parallel_size: 1
  expert_tensor_parallel_size: 1
  finalize_model_grads_func: null
  fp16: false
  grad_scale_func: null
  grad_sync_func: null
  gradient_accumulation_fusion: false
  hierarchical_context_parallel_sizes: null
  microbatch_group_size_per_vp_stage: 1
  moe_extended_tp: false
  no_sync_func: null
  num_microbatches_with_partial_activation_checkpoints: null
  overlap_p2p_comm: false
  overlap_p2p_comm_warmup_flush: false
  param_sync_func: null
  params_dtype: torch.float32
  perform_initialization: true
  pipeline_dtype: null
  pipeline_model_parallel_size: 1
  pipeline_model_parallel_split_rank: null
  sequence_parallel: false
  tensor_model_parallel_size: 1
  timers: null
  tp_comm_atomic_ag: false
  tp_comm_atomic_rs: false
  tp_comm_bootstrap_backend: nccl
  tp_comm_bulk_dgrad: true
  tp_comm_bulk_wgrad: true
  tp_comm_overlap: false
  tp_comm_overlap_ag: true
  tp_comm_overlap_disable_fc1: false
  tp_comm_overlap_disable_qkv: false
  tp_comm_overlap_rs: true
  tp_comm_overlap_rs_dgrad: false
  tp_comm_split_ag: true
  tp_comm_split_rs: true
  use_cpu_initialization: false
  use_ring_exchange_p2p: false
  use_te_rng_tracker: false
  variable_seq_lengths: false
  virtual_pipeline_model_parallel_size: null
  wgrad_deferral_limit: 0
optimizer:
  _target_: <function get_base_optimizer at 0x7f7b9afedf30>
  betas:
  - '0.9'
  - '0.99'
  capturable: 'True'
  eps: 1e-10
  lr: '0.0001'
  master_weights: 'True'
  model: null
  optim_type: fusedadam
  sharding: 'False'
  weight_decay: '0.1'
scheduler:
  _target_: <class 'cosmos_predict1.diffusion.training.functional.lr_scheduler.LambdaLinearScheduler'>
  cycle_lengths:
  - '10000000000000'
  f_max:
  - '1.0'
  f_min:
  - '1.0'
  f_start:
  - 1e-06
  verbosity_interval: '0'
  warm_up_steps:
  - '0'
trainer:
  callbacks:
    grad_clip:
      _target_: <class 'cosmos_predict1.utils.callbacks.grad_clip.GradClip'>
      clip_norm: '1.0'
      force_finite: 'True'
      fsdp_enabled: 'False'
      model_key: model
    iter_speed:
      _target_: <class 'cosmos_predict1.diffusion.training.callbacks.iter_speed.IterSpeed'>
      every_n: '10'
      hit_thres: '0'
    low_prec:
      _target_: <class 'cosmos_predict1.diffusion.training.callbacks.low_precision.LowPrecisionCallback'>
      config: null
      trainer: null
      update_iter: '1'
    progress_bar:
      _target_: <class 'cosmos_predict1.utils.callback.ProgressBarCallback'>
      config: null
      trainer: null
  cudnn:
    benchmark: 'True'
    deterministic: 'False'
  ddp:
    broadcast_buffers: 'True'
    find_unused_parameters: 'True'
    static_graph: 'False'
  distributed_parallelism: ddp
  grad_accum_iter: '4'
  grad_scaler_args:
    enabled: 'False'
  logging_iter: '200'
  max_iter: '5000'
  max_val_iter: null
  memory_format: torch.preserve_format
  run_validation: 'False'
  seed: '0'
  timeout_period: '999999999'
  type: <class 'cosmos_predict1.utils.trainer.Trainer'>
  validation_iter: '100'
