# .devcontainer/bashrc
# カラー プロンプト
if [ "$TERM" != "dumb" ]; then
  export PS1="\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\$ "
fi

# 色付き ls / grep
alias ls='ls --color=auto'
alias grep='grep --color=auto'
